[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "cp -r public .next/standalone/public",
  "cp -r .next/static .next/standalone/.next/static"
]

[start]
cmd = "node .next/standalone/server.js"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
HOSTNAME = "0.0.0.0"
PORT = "3000"
